debug = false

[server]
http_port = 5000
host = "127.0.0.1"

[log]
level = "info"
color = true
prefix = "RustBlog"

[admin]
username = "admin"
password = "12345"
jwt_secret = "12345"
jwt_expire_hours = 24

[database]
url = "sqlite://blog.db?mode=rwc"

[app]
use_content_as_abs = true
max_content_length = 120
custom_empty_abs = "<code>Sorry</code>该文章暂无概述"
